# Generated by Django 6.0.3 on 2026-04-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.customprompt'),
        ),
        migrations.AddField(
            model_name='project',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.customprompt'),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='ai_name',
            field=models.CharField(default='olo', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='context_warning_limit',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='customprompt',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Si es true, se usa como prompt global por defecto.'),
        ),
        migrations.AlterField(
            model_name='customprompt',
            name='title',
            field=models.CharField(help_text='Ej: Contexto Enfermería, Contexto Programación', max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='color',
            field=models.CharField(default='border-blue-400', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='NotebookMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='study.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='study.project')),
            ],
        ),
    ]
