# Generated by Django 6.0.7 on 2026-09-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_passkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passkey',
        ),
    ]
