# Generated by Django 6.0.3 on 2026-03-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='Ej: Ciberseguridad, Cloud, Scripts', max_length=100)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(help_text='Ej: bash, json, python', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sebastian Villalba', max_length=100)),
                ('hero_title', models.CharField(help_text='Ej: Ingeniería con propósito.', max_length=200)),
                ('bio_p1', models.TextField(help_text='Primer párrafo (Ej: Camino desde Enfermería...)')),
                ('bio_p2', models.TextField(help_text='Segundo párrafo (Ej: Rigurosidad aplicada a Software...)')),
                ('location', models.CharField(default='Buenos Aires, ARG', max_length=100)),
                ('origin', models.CharField(default='Paraguay', max_length=100)),
                ('languages', models.CharField(default='ES / EN / KR (Basic)', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('work_philosophy', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('arsenal', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True, help_text='Punto verde en el footer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Ej: vexa-os', unique=True)),
                ('category', models.CharField(help_text='Ej: Full-stack, Infra & Cloud', max_length=100)),
                ('short_description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_public', models.BooleanField(default=True, help_text='Si es False, solo se ve en The Forge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
