# Generated by Django 6.0.3 on 2026-03-22 02:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='arsenal',
            field=models.JSONField(blank=True, default=api.models.default_arsenal),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.JSONField(blank=True, default=api.models.default_education),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_philosophy',
            field=models.JSONField(blank=True, default=api.models.default_work_philosophy),
        ),
    ]
