# Generated by Django 6.0.3 on 2026-03-22 02:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_arsenal_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.AddField(
            model_name='project',
            name='analysis_text',
            field=models.TextField(blank=True, help_text='Párrafo explicando el enfoque de seguridad o arquitectura.'),
        ),
        migrations.AddField(
            model_name='project',
            name='changelog',
            field=models.JSONField(blank=True, default=api.models.default_changelog),
        ),
        migrations.AddField(
            model_name='project',
            name='clone_cmd',
            field=models.CharField(blank=True, help_text='Comando git clone...', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='core_code',
            field=models.TextField(blank=True, help_text='Bloque de código destacado para mostrar.'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='Ej: [{"image": "url", "caption": "...", "desc": "..."}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_class',
            field=models.CharField(default='from-zinc-800 via-zinc-900 to-black', help_text='Clases Tailwind para el fondo', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(default='server', help_text='Nombre del icono Lucide (ej: server, layout, shield)', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='projects/main/'),
        ),
        migrations.AddField(
            model_name='project',
            name='install_steps',
            field=models.JSONField(blank=True, default=api.models.default_install_steps),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.JSONField(blank=True, default=api.models.default_links),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.JSONField(blank=True, default=api.models.default_metrics),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Para ordenar en la lista (menor = primero)'),
        ),
        migrations.AddField(
            model_name='project',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='Ej: ["Mínimo 512MB RAM"]'),
        ),
        migrations.AddField(
            model_name='project',
            name='structure',
            field=models.JSONField(blank=True, default=api.models.default_structure),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default=2, help_text='Ej: Sistema Operativo, E-commerce', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, help_text='Ej: v1.0.4-stable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(help_text='Ej: Infra & Cloud, Frontend, Full-stack', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='highlights',
            field=models.JSONField(default=list, help_text='Ej: ["Diseño API REST", "Seguridad"]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text='Ej: ["Next.js", "Django"]'),
        ),
    ]
