# Generated by Django 6.0.3 on 2026-03-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_options_remove_project_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ej: https://www.youtube.com/watch?v=dQw4w9WgXcQ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='analysis_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='clone_cmd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='core_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='gradient_class',
            field=models.CharField(default='from-zinc-800 via-zinc-900 to-black', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_name',
            field=models.CharField(default='server', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.project')),
            ],
        ),
    ]
