# Generated by Django 6.0.3 on 2026-03-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_gallery_project_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labsnippet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='labsnippet',
            name='code_snippet',
        ),
        migrations.AddField(
            model_name='labsnippet',
            name='code',
            field=models.TextField(default=1, help_text='El fragmento de código, script o prompt.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labsnippet',
            name='icon_name',
            field=models.CharField(default='terminal', help_text='Ícono Lucide (Ej: shield, cloud, terminal, sparkles)', max_length=50),
        ),
        migrations.AddField(
            model_name='labsnippet',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Ej: ["linux", "ufw", "security"]'),
        ),
        migrations.AlterField(
            model_name='labsnippet',
            name='category',
            field=models.CharField(help_text='Para filtrar en el sidebar (Ej: Ciberseguridad, Cloud, Scripts)', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsnippet',
            name='description',
            field=models.TextField(help_text='Descripción de para qué sirve este fragmento.'),
        ),
        migrations.AlterField(
            model_name='labsnippet',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si es False, se oculta del Lab público'),
        ),
        migrations.AlterField(
            model_name='labsnippet',
            name='language',
            field=models.CharField(default='bash', help_text='Lenguaje para el syntax (Ej: bash, json, text, python)', max_length=50),
        ),
        migrations.AlterField(
            model_name='labsnippet',
            name='title',
            field=models.CharField(help_text='Ej: Hardening básico en Debian', max_length=200),
        ),
    ]
