# Generated by Django 6.0.3 on 2026-03-22 17:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_labsnippet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.JSONField(blank=True, default=api.models.default_certifications),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=api.models.default_social_links),
        ),
    ]
