# Generated by Django 6.0.3 on 2026-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_certifications_profile_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Ej: view, click, download', max_length=50)),
                ('target', models.CharField(help_text='Ej: home, cv, github, silo-ecommerce', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
