# Generated by Django 6.0.3 on 2026-03-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Para evitar spam de F5', null=True),
        ),
    ]
