# Generated by Django 6.0.4 on 2026-05-07 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_telemetryevent_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('event_date', models.DateField(help_text='Fecha real en la que ocurrió el evento')),
                ('brief_description', models.CharField(help_text='Resumen corto para la vista principal', max_length=300)),
                ('content', models.TextField(help_text='Todo el detalle, lo que aprendiste, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='TimelineMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='timeline_media/')),
                ('caption', models.CharField(blank=True, help_text='Pie de foto opcional', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.timelineevent')),
            ],
        ),
    ]
