# Generated by Django 6.0.4 on 2026-05-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_timelineevent_timelinemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='brief_description',
            field=models.TextField(help_text='Resumen corto para la vista principal'),
        ),
    ]
