# Generated by Django 6.0.7 on 2026-09-12 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_timelineevent_brief_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: iPhone de Seba', max_length=255)),
                ('credential_id', models.TextField(help_text='ID de la credencial en Base64URL', unique=True)),
                ('public_key', models.TextField(help_text='Llave pública en Base64URL')),
                ('sign_count', models.IntegerField(default=0, help_text='Contador de firmas para evitar clonación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
