# Generated by Django 6.0.7 on 2026-10-03 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_passkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='Directo', max_length=50)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('cv_views', models.PositiveIntegerField(default=0)),
                ('cv_downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'source')},
            },
        ),
    ]
