# Generated by Django 6.0.4 on 2026-05-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Por hacer'), ('in_progress', 'En progreso'), ('testing', 'En pruebas'), ('done', 'Listo')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Visión general del proyecto')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Fecha estimada de finalización', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(blank=True, help_text='Ej: v1.0.1, opcional', max_length=50)),
                ('log_type', models.CharField(choices=[('feature', 'Nueva Función'), ('bugfix', 'Corrección de Error'), ('note', 'Nota / Idea'), ('refactor', 'Mejora de Código')], default='note', max_length=20)),
                ('content', models.TextField(help_text='Registro completo de lo que se hizo')),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='planner.workmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='planner.workproject'),
        ),
    ]
